Blog/Models/DomainModels/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Blog.Models.DomainModels
{
    public class Comment
    {

        public int Id { set; get; }

        [Required]
        [AllowHtml]
        public string Text { set; get; }

        [Required]
        public string CreatorEmail { set; get; }

        public DateTime PostDate { set; get; }

        public int PostId { set; get; }
    }
}

Blog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.Models.DomainModels;
using Blog.Repositories;

namespace Blog.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddPost()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult AddPost(Post post)
        {
            PostRepository postRepos=new PostRepository();
            postRepos.Add(post); 
            return RedirectToAction("Index","Home");
        }
        public ActionResult ListPost()
        {
            PostRepository postRepos = new PostRepository();
            ICollection<Post> model = postRepos.GetAll();
            return View();
        }


    }
}

Blog/Controllers/ArticleController.cs
using Blog.Models.DomainModels;
using Blog.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        //
        // GET: /Article/
        PostRepository postRepos;
        CommentRepository commentRepos;


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewComments(int postId)
        {
            commentRepos = new CommentRepository();
            return PartialView("_Comments", commentRepos.GetByPostId(postId));
        }

        [HttpPost]
        public ActionResult AddComment(int postId,string userEmail,string commentText)
        {
            commentRepos = new CommentRepository();
            commentRepos.Add(new Comment
            {
                Text = commentText,
                PostDate=DateTime.Now,
                CreatorEmail = userEmail,
                PostId=postId
            });
            return PartialView("_Comments", commentRepos.GetByPostId(postId));
        }

        [HttpPost]
        public ActionResult DeleteComment(int postId,int commentId)
        {
            commentRepos = new CommentRepository();
            commentRepos.Delete(commentId);
            return PartialView("_Comments", commentRepos.GetByPostId(postId));
        }
    }
}

Blog/Views/Shared/_Comments.cshtml
@model ICollection<Blog.Models.DomainModels.Comment>
    @foreach (var comment in Model)
    {
        <div class="comment">
            <input type="hidden" name="comment_id" class="comment_id" value="@comment.Id"/>
            <span class="delete_comment">x</span>
            <b>@comment.CreatorEmail</b>
            <p>@Html.Raw(comment.Text)</p>
            <span>@comment.PostDate</span>
        </div>
    }

Blog/Views/Shared/_LastPosts.cshtml
@model ICollection<Blog.Models.DomainModels.Post>
<ul class="last_post">
    @foreach (var post in Model)
    {
        <li>
            @Html.ActionLink(post.Title, "Article", "Home", new { id = post.Id }, null)
        </li>
    }
</ul>

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/css/Site.css")" rel="stylesheet" type="text/css" />


    <script src="@Url.Content("~/Content/js/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/ckeditor/ckeditor.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Content/js/jquery.js")" type="text/javascript"></script>

    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    <script>
        $(document).ready(function () {
            $('.ckeditor').ckeditor();
        });
    </script>

</head>
<body>
    <div id="container">
        <div id="header">
            <h1><a href="http://all-free-download.com/free-website-templates/">mini<strong>BLOG</strong> 1.0</a></h1>
            <h2>dont know how to implement this</h2>
            <ul id="nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Admin Area", "Index", "Admin")</li>
            </ul>
        </div>
        <div id="sidebar">
            @*<h1>The Sidebar</h1>
    <p> This is where you will put anything that uhm, belongs here really. Latest Comments. Submenus. Blogrolls. Affiliates. Anything! </p>*@

        <div class="submenu">
            <div class="small_title">Last Post</div>
            @{Html.RenderAction("LastPost", "Home");}
                </div>
                        <div class="submenu">
            <div class="small_title">Links</div>
            <ul class="link_menu">
                <li><a href="#">Six Shooter Media</a></li>
                <li><a href="#">JamesKoster.co.uk</a></li>
                <li><a href="#">Buy a Button!</a></li>
                <li><a href="#">Open Web Design</a></li>
                <li><a href="#">OSWD</a></li>
            </ul>
                            </div>
            <p class="note">Here is a special paragraph for any important notes that you might want to display. </p>
    </div>
    <div id="content">
            @RenderBody()
    </div>
        <div id="footer">
            <p>
                Template design by <a href="#">Six Shooter Media</a>.<br>
                © All your copyright information here.
            </p>
        </div>
    </div>
</body>
</html>

Blog/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}